# Generated by Django 4.0.5 on 2022-06-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_date_publication_bloguer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
